'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:4.0.30319.42000
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    '類別透過 ResGen 或 Visual Studio 這類工具。
    '若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    '(利用 /str 選項)，或重建您的 VS 專案。
    '''<summary>
    '''  用於查詢當地語系化字串等的強類型資源類別。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  傳回這個類別使用的快取的 ResourceManager 執行個體。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("_ChenPingPOS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        '''  使用這個強類型資源類別的資源查閱。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property _exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property add() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property bACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property back_after1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_after1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property back_before1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_before1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property backspace() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backspace", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property bake() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bake", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property bluebutton() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bluebutton", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property business_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("business_report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property button__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button__1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property button_after() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_after", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property button_before() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_before", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property clipboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property cooking_pots() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cooking_pots", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property done() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("done", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property donee() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("donee", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property green_1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_1_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property green_box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property green_box2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("green_box2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property harvest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("harvest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        '''</summary>
        Friend ReadOnly Property icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property IMG_0252() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_0252", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property IMG_0256() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IMG_0256", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property loupe() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("loupe", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property material() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("material", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property money() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property notes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property number1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("number1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property number2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("number2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property number3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("number3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property number4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("number4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property number5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("number5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property okorder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("okorder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property order() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("order", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property red_box() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_box", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property red_box2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("red_box2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property redo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property redo_after() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redo_after", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property revise() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("revise", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property ribbon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ribbon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property search2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property square() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property square1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property square2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property square3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("square3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property totem_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("totem_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property totem_r() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("totem_r", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property totem_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("totem_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property trianglify_lowres__2_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trianglify_lowres__2_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property trianglify_lowres__3_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trianglify_lowres__3_", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property yellow1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yellow1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 加() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("加", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 報表() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("報表", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 後() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("後", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 按鈕() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("按鈕", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 按鈕藍() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("按鈕藍", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 排名底() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("排名底", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 減() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("減", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        '''</summary>
        Friend ReadOnly Property 陳品logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("陳品logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
